# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity_unique',
            fields=[
                ('NIS', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('First_Name', models.CharField(max_length=80, null=True)),
                ('Last_Name', models.CharField(max_length=80, null=True)),
                ('Residence', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
