# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity_unique',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
