# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom_name', models.CharField(default='', max_length=80)),
                ('Symptom_description', models.TextField(default='', max_length=1000)),
                ('Unique_Identity', models.ManyToManyField(to='nesting.Identity_unique')),
            ],
        ),
    ]
