# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0002_symptom_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom_relation',
            name='Unique_Identity',
        ),
        migrations.AddField(
            model_name='symptom_relation',
            name='NIS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nesting.Identity_unique'),
        ),
    ]
