# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0002_identity_unique_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity_unique',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
