# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0003_auto_20171017_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom_relation',
            name='NIS',
        ),
        migrations.AddField(
            model_name='symptom_relation',
            name='Unique_Identity',
            field=models.ManyToManyField(to='nesting.Identity_unique'),
        ),
    ]
