# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0003_identity_unique_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity_unique',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
