# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0005_auto_20171017_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity_unique',
            name='First_Name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='identity_unique',
            name='Last_Name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
