# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0005_auto_20171015_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity_unique',
            name='Contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
