# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0006_auto_20171015_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_Treatment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Diseases',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='Symptoms_description',
            field=models.TextField(max_length=900, null=True),
        ),
    ]
