# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0007_auto_20171015_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='Unique_Identities',
            field=models.ManyToManyField(to='nesting.Identity_unique'),
        ),
    ]
